---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sample-cluster-development
  namespace: acm-subscriptions
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: managed/ostoy/sample-cluster
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: sample-cluster-development
spec:
  channel: acm-configuration/acm-applications
  placement:
    placementRef:
      name: sample-cluster-development
      kind: PlacementRule