---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sample-cluster-ostoy
  namespace: acm-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - key: deploymentype
        operator: In
        values:
          - sample-cluster